### ISSUE TITLE
VS Code View

### ISSUE THREAD

**Issue by thezachdrake** [JuliaEarth/GeoTables.jl#120]
Some other `Tables.jl` implementations allow for a `view` when working in VS Code, specially `DataFrames.jl`. If using the Julia extension for VS code, and a `DataFrame` object is loaded into memory, it can be seen in the Julia REPL Workspace with a little eyeball icon next to it. When clicking this it loads the table into a viewer in the VS Code editor where it can be explored visually. This is super useful when just trying to look over the whole data set for sanity checks or discussions with colleagues. Not sure if this is implemented on the tables side or the VS Code side. My inclination is this feature should work with `Tables.jl `implementations.

**Comment by juliohm** [comment]
@thezachdrake please update the environment to get the new feature. The new release should be out in 15min: https://github.com/JuliaRegistries/General/pull/110354

**Comment by thezachdrake** [comment]
Wow!!!! 3 hours and you deployed this already? #SuperMaintainer

**Comment by juliohm** [comment]
Thank @eliascarv for this :)

Em qua., 3 de jul. de 2024, 15:05, Zach Drake ***@***.***>
escreveu:
