### ISSUE TITLE
Load a GeoPackage dataset

### ISSUE THREAD

**Issue by ErickChacon** [JuliaEarth/GeoTables.jl#13]
I have a problem loading a GeoPackage dataset (https://drive.google.com/file/d/16--kcGrC56zayrK04-Brmfo3ImOwtQ5k/view?usp=sharing). The dataset can be loaded using ArchGDAL.

```julia
import ArchGDAL as AG
using DataFrames
stations = @chain "stations.gpkg" begin
    AG.read()
    AG.getlayer(0)
    DataFrame()
end
```

However, I can not load it using GeoTables.

```julia
using GeoTables
@time stations = GeoTables.load("stations.gpkg")
```

The previous code does not finish to be executed. I am using the latest version of `GeoTables.jl`.

**Comment by juliohm** [comment]
@ErickChacon I can reproduce the issue. Nailed it down to a specific function call.

First we load the GDAL geometries:

```julia
using GeoTables

# auxiliary packages
import ArchGDAL as AG
import Tables

# load layer as a Tables.jl table
data  = AG.read("stations.gpkg")
table = AG.getlayer(data, 0)

# get the column with geometries
cols  = Tables.columns(table)
geoms = Tables.getcolumn(cols, :geom)
2-element Vector{ArchGDAL.IGeometry{ArchGDAL.wkbPoint}}:
 Geometry: POINT (-77.55011 -11.06068)
 Geometry: POINT (-77.36839 -11.36014)
```

Second we try to convert to Meshes.jl geometries:

```julia
# convert GDAL geometries to Meshes.jl geometries
items = GeoTables.geom2meshes.(geoms)
```

but the function `GeoTables.geom2meshes` hangs now.

It used to work, but the GeoInterface.jl is a never ending effort to convert geometry types, so our function may be broken now. Can you please check if [our implementation](https://github.com/JuliaEarth/GeoTables.jl/blob/802c2492edb9b5d8f795c36c8f2dc6d7aa184f4d/src/conversion.jl#L39-L72) is up-to-date and is the most efficient?

Feel free to submit a PR if you discover what is causing the function call to hang now.

**Comment by ErickChacon** [comment]
Hi @juliohm. Thank for the explanation. This is something that I need so I will take a look to `geom2meshes` and `GeoInterface.jl`. I will come back when I find the issue.

**Comment by juliohm** [comment]
Thank you @ErickChacon , this issue must be specific to GDAL because the same function works with Shapefile.jl and GeoJSON.jl geometries.

**Comment by ErickChacon** [comment]
HI @juliohm. Yes, this is specific of GDAL but is not clear for me why it does not work. Continuing with your example. We can easily conver the first point with:

```julia
using Meshes
GI.coordinates(geoms[1]) |> Point
```
However a simple function like the following does not work (it hangs):

```julia
function topoint(geom)
    coords = GI.coordinates(geom)
    Point(coords)
end
topoint(geoms[1])
```

If I splat the coordinates vector, it works without problem.
```julia
function topoint2(geom)
    coords = GI.coordinates(geom)
    Point(coords...)
end
topoint2(geoms[1])
```

I have tried other options like using the `GeoInterface.convert` approach, but the same problem occurs when trying to create the `Point` from the coordinates vector. To isolate the problem I do not load `Geotables` at all. Let me know if yout have any thought about how to proceed.

**Comment by juliohm** [comment]
Thank you @ErickChacon for investigating this further. Can you confirm that the other geometry types from GeoJSON.jl and Shapefile.jl work fine with your topoint function?

Our constructors for Point are defined here: https://github.com/JuliaGeometry/Meshes.jl/blob/master/src/points.jl

**Comment by juliohm** [comment]
I also noticed that this behavior only happens inside a function and that doing it manually with GDAL types on the REPL works. It must be one of the GDAL pointer idiosyncrasies...

**Comment by ErickChacon** [comment]
Exactly, it only happens inside the function. `Shapefile.jl` works without problems for both functions I presented before.

**Comment by juliohm** [comment]
Worth checking with the maintainers of GDAL.jl and ArchGDAL.jl if there is a better method with GeoInterface.jl to make these conversions. I am not following these developments myself.

**Comment by rafaqz** [comment]
The return value of `GI.coordinates` is just a `Vector{Float64}` like it always has been? 

```julia
julia> using ArchGDAL

julia> mypoint = ArchGDAL.createpoint(1.0, 5.0)
Geometry: POINT (1 5)

julia> GeoInterface.coordinates(mypoint)
2-element Vector{Float64}:
 1.0
 5.0
```

`GeoInterface.coordinates` is a pretty stable interface, and not at all part of our ongoing comparability efforts. So this is probably a Meshes.jl problem.

We usually use `GeoInterface.getpoint` in an iteration to do these conversions efficiently these days, and they work pretty nicely for everything else, although of course `ArchGDAL.jl will be slower due to the API overheads.

**Comment by juliohm** [comment]
If you read our comments above you will see that the issue is specific to
GDAL. Whenever we call GI.coordinates from inside a function.

Em qui., 27 de abr. de 2023 11:43, Rafael Schouten ***@***.***>
escreveu:

**Comment by rafaqz** [comment]
```julia
julia> f(geom) = GeoInterface.coordinates(geom)
f (generic function with 1 method)

julia> f(mypoint)
2-element Vector{Float64}:
 1.0
 5.0
```

?

**Comment by juliohm** [comment]
Can you please read the previous comments? The REPL works fine.

Em qui., 27 de abr. de 2023 11:47, Rafael Schouten ***@***.***>
escreveu:

**Comment by juliohm** [comment]
Or you are saying that this is hanging somewhere else down in the
Meshes.Point constructors?

Em qui., 27 de abr. de 2023 11:50, Júlio Hoffimann <
***@***.***> escreveu:

**Comment by rafaqz** [comment]
I mean it has to be right? Or at least some combination? 

Because this works fine everywhere else.

**Comment by ErickChacon** [comment]
I think it might be a combination of both `Meshes.jl` and `ArchGDAL.jl` that does not work. For example, other Meshes constructors for Point work with `ArchGDAL.jl` like the following:

```julia
mypoint = AG.createpoint(1.0, 5.0)
function topoint(geom)
    coords = GI.coordinates(geom)
    Meshes.Point(coords...)
end
topoint(mypoint)
```

**Comment by rafaqz** [comment]
Shapefile.jl will be the same as ArchGDAL.jl.
```
julia> GeoInterface.coordinates(Shapefile.Point(1.0, 5.0))
2-element Vector{Float64}:
 1.0
 5.0
```

It cant be the return values causing this unless you are testing with another floating point type in the other packages and thats not triggering the bug.

So how are you imagining that Meshes.jl would cause a low-level GDAL error that we don't get without GDAL?

What is the mechanism? memory use? For this one point that shouldn't be an issue.

**Comment by ErickChacon** [comment]
Not sure where because the lack of error trace. I also tried using `Debugger.jl`, the wierd thing is that it it does not hang when calling with `@enter topoint(mypoint)`

> But which constructor is hanging? Is it a Julia issue or a low-level issue in GDAL?

**Comment by ErickChacon** [comment]
In particular I am exploring the following contructors https://github.com/JuliaGeometry/Meshes.jl/blob/a0487c6824d6ee9d7389edc25ae937f1e4cf26fd/src/points.jl#L53-L55.

The constructor that uses `Meshes.Vec` does not work with `ArchGDAL` defined in `topoint3`:

```julia
import ArchGDAL as AG
import GeoInterface as GI
using Meshes

mypoint = AG.createpoint(1.0, 5.0)

function topoint1(geom)
    coords = GI.coordinates(geom)
    Meshes.Point(coords...)
end

function topoint2(geom)
    coords = GI.coordinates(geom)
    Meshes.Point{2,Float64}(coords)
end

function topoint3(geom)
    coords = GI.coordinates(geom)
    Meshes.Point(Meshes.Vec(coords))
end

topoint1(mypoint)
topoint2(mypoint)
topoint3(mypoint)
```

**Comment by juliohm** [comment]
Thanks for investigating this further @ErickChacon , can you explain why do you think the call to length could be problematic? Isn't the coordinates vector returned by GI.coordinates a simple Julia Vector?

**Comment by ErickChacon** [comment]
For now, the only reason is because the only intermediate step between `Vec(coords)` and `Vec{2,Float64}(coords)` is the use of `length`, but I am not sure.

**Comment by juliohm** [comment]
@eliascarv can you please double check this?

**Comment by rafaqz** [comment]
My ArchGDAL PR may also reduce the weight from the GDAL side, currently getting points has too much overhead:

https://github.com/yeesian/ArchGDAL.jl/pull/369

It may interact with the poor design of `Vec` here to cause this problem.

**Comment by ErickChacon** [comment]
Investigating a bit further, I could see that it hangs in the following line https://github.com/JuliaGeometry/Meshes.jl/blob/cb556d34900c64b6f40ac827360039c0fb3549f3/src/vectors.jl#L60, but only when interacting with ArchGDAL. It hangs when calling `NTuple{Dim,T}(coords)`.

**Comment by rafaqz** [comment]
Did you make that change?

Also try my ArchGDAL PR for better point performance.

But ultimately using `coordinates` is not the way to do this. You are losing the compile-time known 2d/3e length and getting it back again at runtime from the lowest point level in a geometry. Its terrible for performance no matter what you do.

Iterating over `GI.getgeom(geom)` with `GI.x` and `GI.y`, and `GI.is3d` to get the `D` parameter is the way to do it fast.

**Comment by juliohm** [comment]
It would help if this "preferred new way" of doing things with GI was implemented somewhere for reference. We could just copy/paste the code that is supposedly fast and more aligned with the latest version of the interface.

**Comment by ErickChacon** [comment]
> Did you make that change?

When I say that it hangs when calling `NTuple{Dim,T}(coords)`, I mean without any change in `Meshes.jl`. But I agree with you that the main issue is by using `length` in the constructor make it non typestable. If I follow your suggestion, it works as long as `length` is not used inside the definiction of `Vec`. The question there would be how to generalize this constructor for higher dimensions?

> Also try my ArchGDAL PR for better point performance.
> 
> But ultimately using `coordinates` is not the way to do this. You are losing the compile-time known 2d/3d length and getting it back again at runtime from the lowest point level in a geometry. Its terrible for performance no matter what you do.
> 
> Iterating over `GI.getgeom(geom)` with `GI.x` and `GI.y`, and `GI.is3d` to get the `D` parameter is the way to do it fast.

Happy to follow that approach. As @juliohm mentioned, which package would you suggest to check for the geointerface implementation? GeometryBasics.jl?

**Comment by ErickChacon** [comment]
I can confirm that using the following constructor solves the problem and passes all test. @juliohm would you like a pull request on `Meshes.jl`?

```julia
function Vec(coords::AbstractVector{T}) where {T}
    n = length(coords)
    if n == 1
        Vec{1,T}(coords)
    elseif n == 2
        Vec{2,T}(coords)
    elseif n == 3
        Vec{3,T}(coords)
    else
        throw(ErrorException("not implemented"))
    end
end
```

Of course, it would still be great to update the geointerface for `Meshes.jl` depending of the package @rafaqz suggest to look at.

**Comment by juliohm** [comment]
@ErickChacon a PR request would be very welcome. The code you shared seems fine, I think we can assume that Meshes.jl only supports up to 3 dimensions currently.

**Comment by rafaqz** [comment]
Maybe LibGEOS.jl is the best to compare to?

https://github.com/JuliaGeo/LibGEOS.jl/blob/master/src/geo_interface.jl

You may also notice that it accepts all GeoInterface.jl objects in all functions without explicit conversions by users.

 That could also work in Meshes.jl

**Comment by rafaqz** [comment]
It may be eaaiest to follpw this PR:

https://github.com/JuliaGeo/LibGEOS.jl/pull/156

**Comment by juliohm** [comment]
This has to do with the fact that GI returns a Union{Vector{T}, Vector{Union{T,Nothing}} etc as the resulting type. This is a MWE where Julia apparently has a bug:

```julia
test(v::AbstractVector{T}) where {T} = NTuple{length(v),T}(v)

test([1,2,3]) # works

test([1,2,nothing]) # hangs
```

Thanks @eliascarv for finding this MWE.

**Comment by rafaqz** [comment]
That's interesting, does seem like some kind of compiler bug.

But that return type sucks, we should track down where that comes from.

**Comment by juliohm** [comment]
@ErickChacon you mentioned that we could fix the issue here by avoiding that constructor, right? Can you prepare a PR here as well to use the splatting operator as you suggested? It would be great if you could create a test set with GDAL geometries making sure that our geom2meshes function is working as expected with all of them.

**Comment by ErickChacon** [comment]
@juliohm, yes. I am checking https://github.com/JuliaGeo/LibGEOS.jl/blob/master/src/geo_interface.jl to make the interface similar to it. We will just use `GI.x`, `GI.y`, and `GI.z` as used in `LibGEOS.jl`. They use the following function.

```julia
function GI.convert(::Type{Point}, ::PointTrait, geom; context=get_global_context())
    if GI.is3d(geom)
        return Point(GI.x(geom), GI.y(geom), GI.z(geom), context)
    else
        return Point(GI.x(geom), GI.y(geom), context)
    end
end
```

I am still checking other details to have an interface aligned with @rafaqz suggestions. I will start a pull request soon.

**Comment by rafaqz** [comment]
FYI `context` is purely an annoying libgeos thing ;)

But otherwise that should be generic

**Comment by rafaqz** [comment]
FYI `context` is purely an annoying libgeos thing ;)

But otherwise that should be generic.


Also note Meshes.jl will need a `Meshes.geointerface_geomtype` method to implement package level conversions.

Probably all this code should be in extensions in Meshes.jl anyway at some point, the dependencies on GeoJSON.jl and Shapefile.jl are obsolete now, they have Tables.jl interfaces.

**Comment by juliohm** [comment]
We don't have plans to add dependencies related to GeoInterface.jl in Meshes.jl, it is not aligned with our philosophy and we don't want to promote use cases where users are fiddling with different geometry types all over the place. We are providing these conversion methods here in GeoTables.jl so that people can do IO, proceed with geometric processing constrained to a single set of geometries in Meshes.jl, and then export the results back to disk. That is the only place where GeoInterface.jl is envisioned in our stack.

**Comment by rafaqz** [comment]
Sure thing, love the strict, clean philosophy!

But mostly the idea is that theres no fiddling to be done, interop will be seemless ;)

**Comment by juliohm** [comment]
> But mostly the idea is that theres no fiddling to be done, interop will be seemless ;)

Perhaps you are too optimistic about the co-existence of different geometry types in advanced geometric processing pipelines. At some point you will hit function calls that are not implemented in terms of the GeoInterface.jl and the application will just crash. It is as simple as that in my mind, but I would be happy to be proven wrong. Looking forward to the seamless experience!

**Comment by rafaqz** [comment]
Its actually pretty easy to add methods for all functions in a package to accept GeoInterface types. See e.g. my LinGEOS PR. There is very little code used on that interop.

**Comment by juliohm** [comment]
Thank you @ErickChacon for fixing this ❤️
