### ISSUE TITLE
create GeoTable from GeoDataFrame

### ISSUE THREAD

**Issue by visr** [JuliaEarth/GeoTables.jl#2]
I see you're using GeoInterface to convert the Shapefile geometries to Meshes. Note that that code should also work the same on other geometries, such as the ArchGDAL geometries used in https://github.com/evetion/GeoDataFrames.jl.

Since GDAL has much better IO coverage than only the Shapefile that is currently supported here, it would be nice to add a conversion function. No additional dependencies needed, users could just

```julia
using GeoDataFrames, GeoTables
df = GeoDataFrames.read("rivers.gpkg")
table = GeoTable(df)  # or another method
```

**Comment by juliohm** [comment]
We thought of using ArchGDAL.jl directly, which is what GeoDataFrames.jl is doing behind the scenes:

```julia
function load_gpkg(fname, layerid=0)
  gpkg = AG.read(fname)
  layer = AG.getlayer(gpkg, layerid)
  table = AG.Table(layer)
end
```

One thing that a colleague pointed out is that GPKG and other formats allow the storage of multiple layers with different geometries. So perhaps the function `GeoTables.load` should accept a `layerid` option as well.

**Comment by visr** [comment]
Yep, that would work as well. Indeed GeoDataFrames also has a `layer` argument, see also https://github.com/evetion/GeoDataFrames.jl/issues/15.

**Comment by juliohm** [comment]
Fixed the issue here: https://github.com/JuliaEarth/GeoTables.jl/commit/32847c2c8ef69e3ce04dba00319b98a0678f5f60

Some GPKG files loaded by AG have no schema defined. Is that expected? I see that GeoDataFrames has this line which may be related: https://github.com/evetion/GeoDataFrames.jl/blob/a6ec96bb0a2f4dc0f86304e1b67582525e7ac48b/src/io.jl#L17

**Comment by visr** [comment]
I believe this PR will address those issues: https://github.com/yeesian/ArchGDAL.jl/pull/160

Regarding 32847c2c8ef69e3ce04dba00319b98a0678f5f60, thanks for addressing this quickly, looking at the commit I have two comments about this bit:

```julia
  if endswith(fname, ".shp")
    table = SHP.Table(fname)
  elseif endswith(fname, ".gpkg")
    gpkg  = AG.read(fname)
    data  = AG.getlayer(gpkg, layer)
    table = AG.Table(data)
  else
    throw(ErrorException("Unknown file format"))
  end
```

GDAL provides both Shapefile and GeoPackage, as well as many more formats (https://gdal.org/drivers/vector/index.html), through the same API. If you take the GDAL dependency anyway, I think you can remove the Shapefile special case, the GDAL Shapefile driver is much more robust, and supports for instance .shz, which has the loose files zipped together, see https://gdal.org/drivers/vector/shapefile.html.

So I'd remove the whole if block and just keep

```julia
    gpkg  = AG.read(fname)
    data  = AG.getlayer(gpkg, layer)
    table = AG.Table(data)
```

**Comment by juliohm** [comment]
> I believe this PR will address those issues: [yeesian/ArchGDAL.jl#160](https://github.com/yeesian/ArchGDAL.jl/pull/160)

I scanned the PR quickly but couldn't find the relevant changes. I have these two test GPKG files that don't have a schema via the ArchGDAL.jl commands: https://drive.google.com/drive/folders/1BLJjHG_bBEWslhdBloLXTzBbSnCci0Tl?usp=sharing

Regarding Shapefile.jl vs. ArchGDAL.jl, I would like to remove the dependency on the GDAL binary in the long run. What I will do is change the logic so that GDAL is the default reader when a pure Julia reader is not available:

```julia
if endswith(fname, ".shp")
  SHP.Table(fname)
else # fallsback to GDAL
  ...
end
```

That way we cover more files by default.

**Comment by juliohm** [comment]
Fixed in https://github.com/JuliaEarth/GeoTables.jl/commit/cef70f5ce0e5e835d42574a36ab3a4cf3be1e761

The only missing issue now is the schema. If you have an easy fix for it, please let me know.

**Comment by visr** [comment]
This is on that ArchGDAL PR branch, this seems to have a schema right? Or is that not what you mean?

```julia
julia> import ArchGDAL as AG

julia> ds = AG.read(raw"c:\Users\visser_mn\Downloads\test1.gpkg")
GDAL Dataset (Driver: GPKG/GeoPackage)
File(s):
  c:\Users\visser_mn\Downloads\test1.gpkg

Number of feature layers: 1
  Layer 0: dados (wkbPoint)


julia> data  = AG.getlayer(ds, 0)
Layer: dados
  Geometry 0 (geom): [wkbPoint], POINT (559970 9582807), ...
     Field 0 (id): [OFTString], MI1968791, MI1968420, MI1967097, GI782847, ...
     Field 1 (x): [OFTReal], 559970.0, 560556.0, 560354.56, 560266.96, ...
     Field 2 (y): [OFTReal], 9.582807e6, 9.582287e6, 9.58258241e6, ...
     Field 3 (z): [OFTReal], 328.28, 282.57, 319.44, 300.17, 370.98, 340.53, ...


julia> table = AG.Table(data)
Table with 52 features


julia> using Tables

julia> Tables.schema(data)
Tables.Schema:
 :geom  ArchGDAL.IGeometry{GDAL.wkbPoint}
 :id    String
 :x     Float64
 :y     Float64
 :z     Float64
```

**Comment by juliohm** [comment]
Oh I didn't realize it was not merged already, sorry for the confusion. It means that we don't need to do anything here then. Thanks for the quick tests. I will mark the issue as solved.
