### ISSUE TITLE
More fixes to show

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/GeoTables.jl#47]
It should

- [x] not materialize the geometry column
- [x] always show the units, even if NoUnits
- [x] remove Missing with nonmissingtype
- [x] show in html with a different method
- [x] adjust styling options

**Comment by Jay-sanjay** [comment]
Hello all , I would be happy to start with this issue , can you please provide sort of hint to how to resolve this issue and what it is related to .

**Comment by juliohm** [comment]
Hi @Jay-sanjay we are already tackling the issue. Thank you for your interest. If you want to contribute with other issues in the stack, you are welcome.

**Comment by Jay-sanjay** [comment]
@juliohm  Yeah sure , thanks for informing :)

**Comment by juliohm** [comment]
Fixed on master.
