### ISSUE TITLE
`push!` and `append!` of GeoTable

### ISSUE THREAD

**Issue by ehgus** [JuliaEarth/GeoTables.jl#72]
This package will be more useful when GeoTable support writing features.
Tables.jl provides a manual of implementation: https://tables.juliadata.org/stable/#Tables.isrowtable

**Comment by juliohm** [comment]
Can you please clarify? The link points to the isrowtable trait in Tables.jl

Em seg., 30 de out. de 2023 03:01, Lee, Dohyeon ***@***.***>
escreveu:
